version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies from pyproject.toml"
      - pip install .

  build:
    commands:
      - echo "Running basic import check"
      - python -c "import app"

artifacts:
  files:
    - '**/*'
  name: qa-codepipeline-build